services:
  postgres:
    image: postgres:18
    container_name: post-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posts
    ports:
      - "5433:5432"
    volumes:
      - post_pgdata:/var/lib/postgresql
    networks:
      - microservices

  posts:
    build: .
    container_name: post-service
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_HOST: post-postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: posts
      KAFKA_BROKERS: kafka:9092
      REDIS_HOST: redis
      MONGO_URI: mongodb://mongo:27017/posts
      AUTH_SERVICE_URL: http://auth-service:3000
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    networks:
      - microservices
    volumes:
      - ./:/usr/src/app
    command: sh -c './wait-for.sh post-postgres:5432 npm run start:dev'

networks:
  microservices:
    external: true

volumes:
  post_pgdata:
